name: tanzu-deploy-workflow
on: [push]
jobs:
  tanzu_deploy_job:
    runs-on: ubuntu-latest
    name: Deploy to Tanzu Platform on Commit

    # Run inside this container
#    container:
#      image: tanzuplatform.azurecr.io/tanzu/tanzu-client
#      options: --privileged

    steps:
#      - name: Tanzu Deploy Step
#        id: tanzu-deploy
#        uses: cpage-pivotal/tanzu-deploy-action
#        with:
#          tanzu_api_token: ${{ secrets.TanzuApiToken }}
#          container_repository: tanzuplatform.azurecr.io
#          container_repository_username: ${{ secrets.RepositoryUsername }}
#          container_repository_password: ${{ secrets.RepositoryPassword }}
#          container_registry: tanzuplatform.azurecr.io/build/{name}
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: tanzuplatform.azurecr.io
          username: ${{ secrets.RepositoryUsername }}
          password: ${{ secrets.RepositoryPassword }}
      - name: Deploy application to Tanzu Platform
        uses: cpage-pivotal/tanzu-deploy-action@f7acf4cb27b3ea71dfdef33ce2901639b61be079
        with:
          tanzu_api_token: ${{ secrets.TanzuApiToken }}
          container_registry: tanzuplatform.azurecr.io/build/ci-spring-sensors
          project: AMER-West
          space: corby-space
