name: tanzu-deploy-workflow
on: [push]
jobs:
  tanzu_deploy_job:
    runs-on: ubuntu-latest
    name: Deploy to Tanzu Platform on Commit

    # Run inside this container
#    container:
#      image: tanzuplatform.azurecr.io/tanzu/tanzu-client
#      options: --privileged

    steps:
#      - name: Tanzu Deploy Step
#        id: tanzu-deploy
#        uses: cpage-pivotal/tanzu-deploy-action
#        with:
#          tanzu_api_token: ${{ secrets.TanzuApiToken }}
#          container_repository: tanzuplatform.azurecr.io
#          container_repository_username: ${{ secrets.RepositoryUsername }}
#          container_repository_password: ${{ secrets.RepositoryPassword }}
#          container_registry: tanzuplatform.azurecr.io/build/{name}
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: tanzuplatform.azurecr.io
          username: ${{ secrets.RepositoryUsername }}
          password: ${{ secrets.RepositoryPassword }}
      - name: Login to Tanzu Platform
        uses: cpage-pivotal/tanzu-deploy-action@f9e442ba0170948d14874dae8be3cc1a29d2468c
        with:
          tanzu_api_token: ${{ secrets.TanzuApiToken }}
      - name: Configure Build Plan
        run: tanzu build config --build-plan-source-type=ucp --containerapp-registry tanzuplatform.azurecr.io/build/{name}
      - name: Set project and space context
        run: tanzu project use AMER-West && tanzu space use corby-space
